### ISSUE TITLE
Hourai Elixir's Immortality incompatible with First Aid

### ISSUE THREAD

**Issue by crzyc** [MoriyaShiine/hourai-elixir#6]
### Mod version (NOT Minecraft version)

Mod Version 1.0.2.2 (tested on 1.12.2 Forge, but likely applies to other versions as well)

### A description of the issue

Title. Since First Aid automatically kills the player upon taking lethal damage to either the head or the body, the Hourai Elixir doesn't activate and the player will still die.

Temporary solution is to globally disable having First Aid killing players after their head/body hearts run out, but that applies to all players.

### Log or crash report

No crash here.

**Comment by MoriyaShiine** [comment]
Hourai Elixir has been on Fabric for 4 years while First Aid is a Forge mod, so they can't be installed together
